sudo: false
language: cpp
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - libc6-i386
      - curl
compiler:
  - clang
before_install:
  - curl https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -o cmake-3.4.0-Linux-x86_64.tar.gz
  - tar xf cmake-3.4.0-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script: git clone https://github.com/llvm-mirror/llvm.git --depth 1 && cd llvm/tools && git clone https://github.com/llvm-mirror/clang.git --depth 1 && cd clang/tools && git clone https://github.com/llvm-mirror/clang-tools-extra.git --depth 1 extra && cd extra && git clone --branch=${TRAVIS_BRANCH} https://github.com/rettichschnidi/clang-tidy-misra.git --depth 1 clang-tidy/misra/ && patch -p1 < clang-tidy/misra/clang-tidy.patch && cd ../../../../ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make VERBOSE=1 -j4 check-tidy-misra
