language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6-i386 curl
  - curl https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.sh -o cmake.sh
  - sudo sh cmake.sh --exclude-subdir --prefix=/usr/local
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install libstdc++-4.8-dev
script: git clone https://github.com/llvm-mirror/llvm.git --depth 1 && cd llvm/tools && git clone https://github.com/llvm-mirror/clang.git --depth 1 && cd clang/tools && git clone https://github.com/llvm-mirror/clang-tools-extra.git --depth 1 extra && cd extra && git clone --branch=${TRAVIS_BRANCH} https://github.com/rettichschnidi/clang-tidy-misra.git --depth 1 clang-tidy/misra/ && patch -p1 < clang-tidy/misra/clang-tidy.patch && cd ../../../../ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ../ && make -j10 check-tidy-misra
